services:
  - type: web
    name: fovdark-gaming
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main_simple:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: DATABASE_URL
        value: postgresql://user:password@hostname:port/database
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: fovdark-gaming.onrender.com,localhost,127.0.0.1
      - key: CORS_ORIGINS
        value: https://fovdark-gaming.onrender.com

databases:
  - name: fovdark-db
    databaseName: fovdark
    user: fovdark_user